// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class Stock
{
    public long StockId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public DateTime LastUpdated { get; set; }
}