// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderService.Domain.Entities;

public partial class Order
{
    public Guid OrderId { get; set; }

    public string PaymentId { get; set; }

    public string Street { get; set; }

    public string ZipCode { get; set; }

    public string City { get; set; }

    public string Locality { get; set; }

    public string PhoneNumber { get; set; }

    public long UserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? AcceptDate { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}